# ruff: noqa: F401
"""Public facade for bounded canonical-transfer reference provenance."""

from .provenance_model import (
    REFERENCE_ALTERNATIVE_LIMIT_V1,
    STACK_REFERENCE_ALTERNATIVE_LIMIT_V1,
    BOUNDED_SCALAR_ALTERNATIVE_LIMIT_V1,
    CALL_PARAMETER_OBJECT_PREFIX_V1,
)
from .provenance_model import (
    ReferenceAtomV1,
    captured_stack_owner_v1,
    is_call_parameter_object_v1,
    _aligned_object_identity_v1,
    call_parameter_owner_v1,
    instantiate_call_parameter_identity_v1,
    ReferenceValueV1,
    finite_reference_value_v1,
    _interned_finite_reference_value_v1,
    join_reference_values_v1,
    ObjectRangeV1,
    ExternalMemoryCopyV1,
    ExternalMemoryWriteV1,
    ExternalOutPointerV1,
    ExternalCallbackRuleV1,
    ExternalCallRuleV1,
    ReferenceCatalogV1,
    ScalarFlagRelationV1,
    _normalized_memory_ranges_v1,
    ReferenceStateV1,
    _MutableReferenceStateViewV1,
    BOTTOM_REFERENCE_V1,
    UNKNOWN_SCALAR_REFERENCE_V1,
    CONFLICT_REFERENCE_V1,
)
from .provenance_branch import (
    _scalar_product,
    _adjust_reference,
    _aligned_object_reference_v1,
    adjust_reference_by_constant_v1,
    _dynamic_stack_region_v1,
    _predicate_value_v1,
    _branch_predicate_node_v1,
    _branch_equality_subject_v1,
    _masked_register_subject_v1,
    _scalar_flag_relation_v1,
    _branch_flag_relation_v1,
    _branch_scalar_constraint_v1,
    _filter_reference_equality_v1,
    _drop_narrowed_allocation_alternatives_v1,
    refine_reference_state_for_branch_v1,
)
from .provenance_coverage import reference_operation_coverage_v2
from .provenance_memory import (
    _memory_keys,
    _ranges_overlap,
    _memory_key_invalidated_v1,
    _memory_value_v1,
    call_argument_values_v1,
    _static_loader_name_v1,
    _module_handle_result_v1,
    _dynamic_export_result_v1,
    _write_range_v1,
    _callback_source_value_v1,
    _callback_instance_keys_v1,
    _interpret_reference_node_v1,
    interpret_reference_expressions_v1,
)
from .provenance_effects import (
    apply_reference_effects_v1,
    _merge_external_call_rules_v1,
    indirect_targets_v1,
)

__all__ = [
    "BOUNDED_SCALAR_ALTERNATIVE_LIMIT_V1",
    "BOTTOM_REFERENCE_V1",
    "CONFLICT_REFERENCE_V1",
    "ExternalCallbackRuleV1",
    "ExternalCallRuleV1",
    "ExternalMemoryCopyV1",
    "ExternalMemoryWriteV1",
    "ExternalOutPointerV1",
    "ObjectRangeV1",
    "ReferenceAtomV1",
    "ReferenceCatalogV1",
    "ReferenceStateV1",
    "ReferenceValueV1",
    "ScalarFlagRelationV1",
    "STACK_REFERENCE_ALTERNATIVE_LIMIT_V1",
    "UNKNOWN_SCALAR_REFERENCE_V1",
    "apply_reference_effects_v1",
    "adjust_reference_by_constant_v1",
    "call_argument_values_v1",
    "finite_reference_value_v1",
    "indirect_targets_v1",
    "interpret_reference_expressions_v1",
    "join_reference_values_v1",
    "reference_operation_coverage_v2",
    "refine_reference_state_for_branch_v1",
]
