"""Canonical cut-view extents and outgoing NUL admission, including aliases."""

from collections.abc import Mapping

from .bisimulation_native_views import native_view_selector
from .bisimulation_projection import _captured_parameter_view, _projection_expression
from .bisimulation_support import BisimulationRefinementError, PROOF_PRIVATE_STACK_BELOW
from .bisimulation_exact_frame import wide_entry_condition
from .bisimulation_stack_scope import scope_expression


_VIEW_ADMISSION_SOURCE = f"""
uint32_t spx_proof_view_admitted(
    uint32_t address, uint32_t extent, uint32_t stack_pointer) {{
  const uint64_t private_low =
      (uint64_t)stack_pointer - UINT64_C({PROOF_PRIVATE_STACK_BELOW});
  const uint64_t private_high =
      (uint64_t)stack_pointer + spx_proof_private_high_offset;
  return stack_pointer >= UINT32_C({PROOF_PRIVATE_STACK_BELOW}) &&
      private_high <= UINT32_MAX && address != UINT32_C(0) &&
      (uint64_t)address + (uint64_t)extent <= UINT64_C(4294967296) &&
      (extent == UINT32_C(0) ||
       (uint64_t)address + extent <= private_low ||
       (uint64_t)address >= private_high);
}}
"""

def stack_admission_expression(*, stack_pointer, high_offset, image_base, image_size, readable_entry=False, wide_domain=False, mutable_entry=False):
    """The same entry-stack domain must hold at a reached successor or call.

    This is a predicate, not an assumption about callers. In particular, a
    downward call adjustment can invalidate a previously admitted stack window.
    The expressions are generated by the checker, never authored C fragments.
    """
    if (any(not isinstance(value, int) or isinstance(value, bool)
            for value in (image_base, image_size))
            or image_base < 0 or image_size <= 0 or image_base + image_size > 1 << 32):
        raise BisimulationRefinementError("proof stack domain has a malformed machine image")
    minimum = f"UINT32_C({PROOF_PRIVATE_STACK_BELOW})"
    below = f"UINT64_C({PROOF_PRIVATE_STACK_BELOW})"
    if (readable_entry or mutable_entry) and wide_domain:
        raise BisimulationRefinementError("stack domain cannot be both conditional and fixed")
    if wide_domain:
        minimum, below = "UINT32_C(4)", "UINT64_C(0)"
    elif readable_entry or mutable_entry:
        condition = wide_entry_condition(readable_entry, mutable_entry)
        minimum = f"({condition} ? UINT32_C(4) : {minimum})"
        below = f"({condition} ? UINT64_C(0) : {below})"
    low = f"((uint64_t)({stack_pointer}) - {below})"
    high = f"((uint64_t)({stack_pointer}) + (uint64_t)({high_offset}))"
    return (f"(({stack_pointer}) >= {minimum} && "
            f"{high} <= UINT32_MAX && ({high} <= UINT64_C({image_base}) || "
            f"{low} >= UINT64_C({image_base + image_size})))")


def nul_view_parameters(interface, operation_id: str) -> frozenset[str]:
    types = interface.type_index()
    return frozenset(
        parameter.identity
        for parameter in interface.operation_index()[operation_id].parameters
        if types[parameter.type_id].nul_terminated
        or types[parameter.type_id].extent_kind == "nul_terminated"
    )


def validate_nul_invariant(sync, nul_view_ids):
    """Expose only terminator witnesses already admitted and transported at this cut."""
    captured = {capture.identity for capture in sync.captures
                if _captured_parameter_view(capture) is not None}

    def visit(value):
        if isinstance(value, Mapping):
            if value.get("op") == "nul_extent" and value.get("name") not in captured & nul_view_ids:
                raise BisimulationRefinementError("NUL invariant requires a canonical captured NUL-view parameter")
            for child in value.values():
                visit(child)
        elif isinstance(value, (list, tuple)):
            for child in value:
                visit(child)

    visit(sync.invariant)


def view_extent_expressions(*, projections, identity, nul_view_ids, state, read, native=False):
    rows = {name: getattr(value, "payload", value) for name, value in projections.items()}
    if any(not isinstance(rows.get(name), Mapping) or rows[name].get("kind") not in {"view", "bytes_view"}
           for name in nul_view_ids):
        raise BisimulationRefinementError("cut omits a canonical NUL-view parameter")
    raw = rows.get(identity)
    if not isinstance(raw, Mapping) or raw.get("kind") not in {"view", "bytes_view"}:
        raise BisimulationRefinementError("cut extent relation requires a captured view")

    def project(value) -> str:
        expression = _projection_expression(value, state=state, read=read)
        if expression is None:
            raise BisimulationRefinementError("cut view extent has no reconstructible projection")
        return expression

    address = project(projections[identity])
    extent_id = raw.get("extent_id")
    if extent_id is not None:
        extent_projection = projections.get(str(extent_id))
        if extent_projection is None:
            raise BisimulationRefinementError("cut view omits its machine-coded extent parameter")
        requested = project(extent_projection)
        visible = requested
    elif isinstance(raw.get("requested_extent"), Mapping):
        requested = project(raw["requested_extent"])
        declared = raw.get("extent")
        visible = (project(declared) if isinstance(declared, Mapping)
                   and declared.get("kind") != "origin_remainder" else None)
    elif raw["kind"] == "bytes_view":
        requested, visible = "UINT32_C(1)", None
    else:
        raise BisimulationRefinementError("cut view has no canonical requested extent")

    # The resolver takes max(requested, matching registered NUL extents).
    # All registrations at one address use the same logical origin oracle.
    nul_extent = f"__CPROVER_uninterpreted_spx_nul_extent((uint32_t)({address}))"
    aliases = " || ".join(
        f"(uint32_t)({address}) == (uint32_t)({project(projections[identity])})"
        for identity in sorted(nul_view_ids)
    )
    reference = (f"((({aliases}) && (uint64_t)({requested}) < (uint64_t)({nul_extent})) "
                 f"? (uint64_t)({nul_extent}) : (uint64_t)({requested}))" if aliases else requested)
    if native:
        reference = f"({identity})->base.extent"
    if visible is None:
        visible = f"(({identity})->base.extent - ({identity})->base.offset)" if native else reference
    minimum = project(raw.get("requested_extent", {"kind": "constant", "value": 1, "width": 32}))
    return dict(address=address, requested=requested, reference=reference, visible=visible,
                nul_extent=nul_extent, minimum=minimum)


def cut_view_extent_relation(*, sync, capture, nul_view_ids: frozenset[str], state: str, read: str, native=False) -> str:
    """Check the canonical decoder against reached view fields and NUL bytes."""
    if _captured_parameter_view(capture) is None:
        raise BisimulationRefinementError("cut extent relation requires a captured view")
    extents = view_extent_expressions(
        projections={c.identity: c.projection for c in sync.captures if c.mode == "machine_codec"},
        identity=capture.identity, nul_view_ids=nul_view_ids, state=state, read=read, native=native)
    address, requested, reference, visible, nul_extent, minimum = (
        extents[key] for key in ("address", "requested", "reference", "visible", "nul_extent", "minimum"))
    name = capture.identity
    clauses = [
        f"(uint64_t)({requested}) <= UINT32_MAX",
        f"(uint64_t)({reference}) <= UINT32_MAX",
        f"({name})->base.extent == (uint64_t)({reference})",
        f"({name})->extent == (uint64_t)({visible})",
        f"(uint64_t)({visible}) <= (uint64_t)({reference})",
        f"spx_proof_view_admitted((uint32_t)({address}), (uint32_t)({reference}), {scope_expression(sync, state)})",
    ]
    if native:
        clauses = [
            f"(uint64_t)({requested}) <= UINT32_MAX",
            f"({name})->base.offset <= ({name})->base.extent",
            f"({name})->base.offset <= (uint64_t)({address})",
            f"({name})->base.extent <= UINT32_MAX",
            f"({name})->extent == (uint64_t)({visible})",
            f"(uint64_t)({visible}) <= ({name})->base.extent - ({name})->base.offset",
            f"spx_proof_view_admitted((uint32_t)((uint64_t)({address}) - ({name})->base.offset), "
            f"(uint32_t)({name})->base.extent, {scope_expression(sync, state)})",
        ]
        if name in nul_view_ids:
            clauses.append(f"(uint64_t)({nul_extent}) <= ({name})->base.extent - ({name})->base.offset")
    if name in nul_view_ids:
        last = f"(uint32_t)((uint64_t)({address}) + (uint64_t)({nul_extent}) - UINT64_C(1))"
        clauses.extend([
            f"({nul_extent}) != UINT32_C(0)",
            f"(uint64_t)({nul_extent}) >= (uint64_t)({minimum})",
            f"spx_proof_view_admitted((uint32_t)({address}), {nul_extent}, {scope_expression(sync, state)})",
            f"{read}({last}, UINT32_C(1)) == UINT32_C(0)",
            f"spx_proof_source_output_read({last}, UINT32_C(1)) == UINT32_C(0)",
        ])
    return " && ".join(f"({clause})" for clause in clauses)


def view_parameter_ids(interface, operation_id, operation_projection, *, native_specs=None):
    parameters = {row.identity: row for row in interface.operation_index()[operation_id].parameters}
    types = interface.type_index()
    result = []
    for row in operation_projection["parameters"]:
        if row["projection"].get("kind") not in {"view", "bytes_view"}:
            continue
        if row["id"] not in parameters:
            raise BisimulationRefinementError("shared view admission requires a canonical non-null parameter")
        logical = types[parameters[row["id"]].type_id]
        if logical.nullable is True and (native_specs is None or
                native_specs.get(row['id'], {}).get('nullable_input') is not True or
                logical.kind != 'view' or logical.extent_kind != 'origin_remainder'):
            raise BisimulationRefinementError("shared view admission requires a canonical non-null parameter")
        result.append(row["id"])
    return sorted(result)


def shared_view_initialization(*, interface, operation_id, operation_projection, sync, proof_function, native_specs=None):
    ids = view_parameter_ids(interface, operation_id, operation_projection, native_specs=native_specs)
    projections = ({row["id"]: row["projection"] for row in operation_projection["parameters"]}
                   if sync is None else {c.identity: c.projection for c in sync.captures
                                         if c.mode == "machine_codec" or c.kind == 'parameter' and c.mode == 'native_view'})
    lines = []
    origin_relations = []
    exposed_counts = []
    if native_specs is not None and ids:
        # The exact segment executes before the portable adapter. Reconstruct
        # its issued origins independently from the same admitted input world;
        # source-only enrollment cannot justify exact service reads after a cut.
        lines.append('  spx_runtime __CPROVER_spx_input_exact_runtime = spx_proof_runtime(&spx_exact_world);')
    for ordinal, identity in enumerate(ids):
        if native_specs is not None and native_specs[identity].get('nullable_input') is True:
            nullable_lines, relations, exposed = _nullable_shared_view_initialization(
                identity=identity, ordinal=ordinal, projection=projections[identity],
                spec=native_specs[identity], sync=sync)
            lines.extend(nullable_lines)
            origin_relations.extend(relations)
            exposed_counts.append(exposed)
            continue
        exposed_counts.append('UINT32_C(1)')
        extents = view_extent_expressions(projections=projections, identity=identity,
            nul_view_ids=nul_view_parameters(interface, operation_id), state="initial_state",
            read="spx_proof_exact_input_read")
        base, extent = f"__CPROVER_spx_view_base_{ordinal}", f"__CPROVER_spx_view_extent_{ordinal}"
        if native_specs is not None:
            spec = native_specs[identity]
            selector = native_view_selector(spec)
            reference = f"__CPROVER_spx_view_reference_{ordinal}"
            lines.extend([
                f"  spx_machine_reference_v1 {reference} = {{0}};",
                f"  const spx_boundary_status __CPROVER_spx_view_status_{ordinal} = "
                f"source_runtime.resolve_reference(source_runtime.context, (uint32_t)({extents['address']}), "
                f"(uint32_t)({extents['requested']}), UINT32_C({spec['permissions']}), {selector}, 0U, 0U, &{reference});",
                f"  __CPROVER_assume((uint64_t)({extents['requested']}) <= UINT32_MAX && "
                f"__CPROVER_spx_view_status_{ordinal} == SPX_BOUNDARY_OK && "
                f"{reference}.offset <= (uint64_t)({extents['address']}));",
            ])
            exact_reference = f"__CPROVER_spx_exact_view_reference_{ordinal}"
            exact_status = f"__CPROVER_spx_exact_view_status_{ordinal}"
            lines.extend([
                f"  spx_machine_reference_v1 {exact_reference} = {{0}};",
                f"  const spx_boundary_status {exact_status} = "
                f"__CPROVER_spx_input_exact_runtime.resolve_reference(__CPROVER_spx_input_exact_runtime.context, "
                f"(uint32_t)({extents['address']}), (uint32_t)({extents['requested']}), "
                f"UINT32_C({spec['permissions']}), {selector}, 0U, 0U, &{exact_reference});",
            ])
            origin_relations.extend([f"{exact_status} == SPX_BOUNDARY_OK", *(
                f"{exact_reference}.{field} == {reference}.{field}"
                for field in ('domain', 'object', 'generation', 'offset', 'extent', 'permissions'))])
            if identity in nul_view_parameters(interface, operation_id):
                lines.append(f"  __CPROVER_assume((uint64_t)({extents['nul_extent']}) <= "
                             f"{reference}.extent - {reference}.offset);")
            extents = {**extents, "address": f"((uint64_t)({extents['address']}) - {reference}.offset)",
                       "reference": f"{reference}.extent"}
        lines.extend([
            f"  const uint32_t {base} = (uint32_t)({extents['address']});",
            f"  const uint64_t {extent} = (uint64_t)({extents['reference']});",
            f"  __CPROVER_assume({extent} <= UINT32_MAX &&",
            f"      spx_proof_view_admitted({base}, (uint32_t){extent}, {scope_expression(sync, "initial_state")}));",
            f"  spx_proof_expose_stack_view({base}, (uint32_t){extent});",
        ])
    count = f"spx_proof_exposed_count == UINT32_C({len(ids)})" if ids else "1"
    if any(value != 'UINT32_C(1)' for value in exposed_counts):
        count = "spx_proof_exposed_count == (" + " + ".join(exposed_counts) + ")"
    if origin_relations:
        count = ' && '.join(f'({clause})' for clause in (count, *origin_relations))
    lines.append(f'  __CPROVER_assert({count}, "spx-bisimulation-shared-view-inputs:{operation_id}:{proof_function}");')
    return lines


def _nullable_shared_view_initialization(*, identity, ordinal, projection, spec, sync):
    """Admit the exact input domain, then check its independent source decoding.

    Public nullable parameter lowering remains closed until cut transport uses
    this representation. Successful resolution is the declared input domain;
    a null result stays in that domain without exposing an invented byte span.
    No source success, metadata or memory equality is assumed here.
    """
    from .machine_overlay_result_views import checked_nullable_input_projection

    raw = checked_nullable_input_projection(getattr(projection, 'payload', projection))
    selector = native_view_selector(spec)
    prefix = f'__CPROVER_spx_nullable_input_{ordinal}'
    exact, source = prefix + '_exact', prefix + '_source'
    request = raw['requested_extent']['value']
    fields = ('domain', 'object', 'generation', 'offset', 'extent', 'permissions')
    lines = []
    # Initialization precedes application effects in both worlds. Read through
    # their actual checked callbacks: the mathematical initial-byte reader does
    # not establish native readability of the pointer's storage.
    for name, read, runtime in ((exact, 'spx_proof_exact_output_read', '__CPROVER_spx_input_exact_runtime'),
                               (source, 'spx_proof_source_output_read', 'source_runtime')):
        address = _projection_expression(raw, state='initial_state', read=read)
        lines.extend([
            f'  const uint32_t {name}_address = (uint32_t)({address});',
            f'  spx_machine_reference_v1 {name}_reference = {{0}};',
            f'  const spx_boundary_status {name}_status = {runtime}.resolve_reference(',
            f'      {runtime}.context, {name}_address, UINT32_C({request}),',
            f'      UINT32_C({spec["permissions"]}), {selector}, 1U, 0U, &{name}_reference);',
        ])
    ref = exact + '_reference'
    base = prefix + '_base'
    lines.extend([
        f'  __CPROVER_assume({exact}_status == SPX_BOUNDARY_OK);',
        f'  uint32_t {base} = 0U;',
        f'  if ({exact}_address != 0U) {{',
        f'    __CPROVER_assume({ref}.offset <= {exact}_address && {ref}.offset <= {ref}.extent &&',
        f'        {ref}.extent <= UINT32_MAX);',
        f'    {base} = (uint32_t)((uint64_t){exact}_address - {ref}.offset);',
        f'    __CPROVER_assume(spx_proof_view_admitted({base}, (uint32_t){ref}.extent, {scope_expression(sync, "initial_state")}));',
        f'    spx_proof_expose_stack_view({base}, (uint32_t){ref}.extent);',
        '  }',
    ])
    canonical_null = ' && '.join(f'{ref}.{field} == 0U' for field in fields)
    relations = [f'{source}_address == {exact}_address', f'{source}_status == SPX_BOUNDARY_OK',
        *(f'{source}_reference.{field} == {ref}.{field}' for field in fields),
        f'({exact}_address == 0U ? ({canonical_null}) : '
        f'({ref}.object != 0U && {ref}.extent - {ref}.offset >= UINT32_C({request})))',
        f'({exact}_address == 0U || spx_proof_world_memory_range_equal({base}, {ref}.extent))']
    return lines, relations, f'(uint32_t)({exact}_address != 0U)'


def source_frame_preservation(operation_id, proof_function):
    return [
        f'  __CPROVER_assert(__CPROVER_spx_source_frame_preserved, "spx-bisimulation-source-frame-preservation:{operation_id}:{proof_function}");',
        "  __CPROVER_assume(__CPROVER_spx_source_frame_preserved);",
    ]


def shared_view_admission_source(*, private_ranges, image_base, image_size, readable_entry=False, mutable_entry=False):
    protected = "\n".join(
        f"  if (extent != 0U && (uint64_t)address < UINT64_C({base + width}) && "
        f"UINT64_C({base}) < end) return 0U;" for base, width in private_ranges)
    stack = stack_admission_expression(stack_pointer="stack_pointer", high_offset="spx_proof_private_high_offset",
                                       image_base=image_base, image_size=image_size, readable_entry=readable_entry, mutable_entry=mutable_entry)
    return f"""
uint32_t spx_proof_view_admitted(uint32_t address, uint32_t extent, uint32_t stack_pointer) {{
  uint64_t end = (uint64_t)address + extent;
{protected}
  return address != 0U && end <= UINT64_C(4294967296) && {stack};
}}
"""

def _cut_view_domain(capture, *, state: str, read: str, sync=None) -> str | None:
    """One predicate for outgoing-cut assertions and resumed-input admission."""
    raw = capture.projection.payload if capture.mode == "native_view" else _captured_parameter_view(capture)
    if raw is None or raw["kind"] != "view":
        return None
    address = _projection_expression(raw, state=state, read=read)
    extent = _projection_expression(raw.get("requested_extent", raw.get("extent")), state=state, read=read)
    if address is None or extent is None:
        raise BisimulationRefinementError(f"cut view {capture.identity!r} lacks a reconstructible range")
    domain = f"spx_proof_view_admitted((uint32_t)({address}), (uint32_t)({extent}), {scope_expression(sync, state)})"

    return f"((uint32_t)({address}) == 0U || {domain})" if capture.mode == "native_view" and capture.encoding["nullable"] else domain
