"""Retain the observed BMP lookup as plain C data; native tests recheck the service."""
import argparse
from hashlib import sha256
from pathlib import Path

MAPPING_SHA='7c1d0cbe71f69c4660bbc7ea5bca1a48ebeedb5740742cc5d297b141c1e653c6'


def generate(mapping, output):
    values=mapping.read_bytes()
    if len(values)!=65536 or sha256(values).hexdigest()!=MAPPING_SHA:
        raise ValueError('not the reviewed Windows-1252 mapping; review a changed service before replacing the backend')
    entries=[(i,b) for i,b in enumerate(values) if b!=(i if i<0x80 or 0xa0<=i<=0xff else ord('?'))]
    text=('/* Observed WideCharToMultiByte(1252, 0), one UTF-16 unit at a time.\n'
          ' * Wine 11.0 runtime; full 65536-byte mapping SHA-256: '+MAPPING_SHA+'\n'
          ' * Generated by generate-best-fit.py; checked against the native API. */\n'
          'static const struct { uint16_t word; unsigned char byte; } windows1252_best_fit[]={\n')
    text+='\n'.join('    '+','.join('{0x%04x,0x%02x}' % entry for entry in entries[i:i+6])+','
                    for i in range(0,len(entries),6))
    output.write_text(text+'\n};\n')


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('mapping',type=Path);p.add_argument('output',type=Path)
    a=p.parse_args();generate(a.mapping,a.output)
