"""Compatibility facade for the relational Stage A package.

New implementation code belongs under :mod:`wincr.relational`. Existing CLI,
tests, and third-party callers may continue importing the historical symbols
from this module.
"""

from __future__ import annotations

import json
import os
import re
import signal
import shutil
import subprocess
import tempfile
import time
from collections import Counter, defaultdict, deque
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, as_completed, wait
from pathlib import Path
from threading import Event
from typing import Any

import capstone
import z3

from .stage_binary import StageABinary, StageAInputError, _parse_stage_a_pe
from .util import sha256_bytes, sha256_file, utc_now, write_json
from .relational.artifacts import write_text_if_changed as _write_text_if_changed
from .relational.build import (
    _check_nix_relational_report,
    _finalize_local_proof_ir,
    _finalize_nix_proof_ir,
    _finalize_proof_ir,
    _find_relational_flake_root,
    _load_contract,
    _locked_flake_input,
    _read_json,
    _relational_nix_build_command,
    _relational_nix_evaluator,
    _remove_relational_build_output,
    _validate_prepared_relational,
    _validate_relational_module_graph,
    _write_relational_module_graph,
    stage_a_build_relational,
)
from .relational.analyses.control import (
    _attach_dynamic_indirect_call_analysis,
    _attach_import_register_analysis,
    _attach_product_graph_analysis,
    _attach_stack_window_analysis,
    _composition_progress,
    _constant_read32_address,
    _dynamic_range_indirect_call_candidates,
    _dynamic_range_indirect_call_shape,
    _immutable_image_u32,
    _immutable_indirect_call_candidates,
    _register_writes_have_address_separations,
    _relational_product_graph,
)
from .relational.analyses.external import (
    _attach_external_call_site_analysis,
    _attach_machine_import_call_contract_analysis,
    _machine_import_call_contract_analysis,
    _semantic_affine_base_offset,
    _external_argument_relation_claims,
    _external_call_site_candidates,
    _register_offset_witness,
    _semantic_add_word_offset,
    _semantic_affine_word_read,
    _semantic_call_push_base,
    _semantic_constant_word,
    _semantic_exact_stack_argument,
    _semantic_external_target_identity,
    _semantic_externalize_register_import_call,
    _semantic_input_register_offset,
    _semantic_word_read,
    _semantic_word_writes_disjoint,
)
from .relational.analyses.invariants import (
    _SemanticZ3Context,
    _attach_invariant_synthesis,
    _local_invariant_seeds,
    _semantic_add,
    _semantic_constant,
    _semantic_edges,
    _semantic_equal,
    _semantic_input_flag,
    _semantic_input_register,
    _semantic_is_boolean,
    _semantic_node_count,
    _semantic_not,
    _semantic_or,
    _semantic_tautology,
    _semantic_unsigned_less,
    _substitute_semantic_bool,
    _substitute_semantic_expr,
    _substitute_semantic_flag,
    _synthesize_relational_invariants,
)
from .relational.analyses.segments import (
    _attach_memory_transition_analysis,
    _attach_register_relation_analysis,
    _attach_segment_refinement_analysis,
    _attach_stack_register_output_claims,
    _direct_call_stack_amount,
    _dynamic_range_register_output_claims,
    _dynamic_range_transfer_claims,
    _import_register_transfer_claims,
    _lower_stack_register_relations,
    _mapped_relocation_image_obligations,
    _paired_stack_guard_claim,
    _paired_stack_word_value_claim,
    _paired_stack_word_write_claim,
    _paired_stack_word_writes_claim,
    _proof_ir,
    _related_word_zero_guard_claim,
    _segment_refinement_candidates,
    _semantic_expr_has_exact_inputs,
    _semantic_expr_registers,
    _stack_read32_sub_output_claim,
    _static_dynamic_pointer_slot_guard_claim,
)
from .relational.analyses.registers import (
    _attach_import_register_invariants,
    _attach_import_seed_address_separations,
    _exact_index_expression,
    _iat_import_register_seed_candidates,
    _iat_seed_read,
    _infer_import_register_invariants,
    _infer_register_output_relation,
    _paired_constant_relation,
    _refine_contract_bounds,
    _register_relation_implies,
    _register_relation_join,
    _semantic_index_from_address,
    _semantic_read_addresses,
    _synthesize_register_relations,
    _target_shaped_register_output_claims,
)
from .relational.analyses.stack import (
    _attach_return_slot_contracts,
    _attach_return_write_address_separations,
    _attach_stack_window_invariants,
    _constant_return_write_requirements,
    _direct_call_push_claim,
    _discover_static_call_return_summaries,
    _reachable_weighted_nonzero_cycle_nodes,
    _return_pop_claim,
    _return_write_separations_cover,
    _semantic_read32_after_writes,
    _semantic_read32_after_writes_address,
    _semantic_read8_after_writes,
    _stack_window_transfer_claims,
)
from .relational.contract import (
    _annotate_flag_liveness,
    _assign_region_targets,
    _check_coverage,
    _check_span_overlap,
    _dynamic_range_relations,
    _import_identity,
    _infer_region_address_separations,
    _inside_executable,
    _machine_import_call_contracts,
    _mapped_relocation_offsets,
    _normalize_contract,
    _normalize_padding,
    _padding_bridge_valid,
    _padding_bytes,
    _raw_base_relocations,
    _register_pairs,
    _semantic_cutpoint_spans,
    _semantic_expr_is_pure,
    _span,
    _static_dynamic_pointer_slots,
    stage_a_generate_relation_contract,
)
from .relational.diagnostics import (
    _check_relational_counterexample,
    _complete_counterexample_assignment,
    _dynamic_pointer_traversal_diagnostic,
    _nonzero_word_guard,
    _read32_input_register_offset,
    _static_dynamic_pointer_seed_diagnostic,
)
from .relational.executor import (
    _collect_certificates,
    _compile_formal_kernel,
    _compile_relational_kernel,
    _failed_shard_hint_path,
    _lean_output_current,
    _persistent_olean_path,
    _relational_cache_dir,
    _relational_proof_jobs,
    _run_lean_relational,
    _run_lean_relational_cached,
)
from .relational.verdict import (
    _certificate_hashes_match,
    _counterexample_assignment,
    _lean_diagnostic,
    _write_incomplete,
    _write_relational_verdict,
)
from .relational.extraction import (
    _assembled_iat_read_candidates,
    _assembled_u32_after_register_writes,
    _behavior_cache_key,
    _behavior_rows,
    _cached_behavior_affected_by_machine_contracts,
    _extract_relational_behaviors,
    _iat_read_classification,
    _read8_after_register_writes,
    _read_behavior_cache,
    _register_offset_write,
    _relational_extraction_semantics_sha256,
    _relational_loader_facts,
    _relational_memory_contracts,
    _relational_semantic_ir,
    _relational_semantic_preflight,
    _run_lean_extractor,
    _semantic_exact_memory_inputs,
    _semantic_memory_expression_pullback_supported,
    _semantic_memory_pullback_support,
    _semantic_memory_reads,
    _semantic_pullback_exact_memory_inputs,
    _semantic_successors,
    _semantic_value_at_path,
    _semantic_x87_load_pullback_supported,
    _unique_import_at_absolute_address,
)
from .relational.lean.generation import (
    _compact_acceptance_blockers,
    _copy_relational_kernel_sources,
    _external_register_policy_replay_candidate,
    _lean_acceptance_empty_stack,
    _lean_acceptance_execution_edge,
    _lean_acceptance_outcome,
    _lean_acceptance_running_node,
    _lean_acceptance_running_target,
    _lean_address_separation,
    _lean_all_append_proof,
    _lean_all_listed_proof,
    _lean_appended_list,
    _lean_appended_proof,
    _lean_behavior_field,
    _lean_behavior_fields_memory_free,
    _lean_bool,
    _lean_bound_index_value,
    _lean_bundle_source,
    _lean_byte_tree_definitions,
    _lean_bytes,
    _lean_code_aliases,
    _lean_compositional_normalized_theorem_source,
    _lean_counterexample_source,
    _lean_direct_append_proof,
    _lean_dynamic_range_argument_claim,
    _lean_dynamic_range_relation,
    _lean_external_target,
    _lean_extraction_source,
    _lean_global_mapping_context_source,
    _lean_identical_state_only_write_registers,
    _lean_identical_state_only_writes_component,
    _lean_immutable_indirect_jump_claim,
    _lean_import_certificate,
    _lean_import_register_seed_claim,
    _lean_index_tree,
    _lean_index_tree_join,
    _lean_machine_call_memory_footprint,
    _lean_machine_call_memory_size,
    _lean_machine_import_call_contract,
    _lean_masked_successor_tautology_proof,
    _lean_normalized_branch_parts,
    _lean_normalized_component_setup,
    _lean_normalized_static_outcome,
    _lean_padding_alias_certificate,
    _lean_paired_stack_word_value_claim,
    _lean_paired_stack_word_write_claim,
    _lean_paired_stack_word_writes_claim,
    _lean_pe,
    _lean_pe_side_source,
    _lean_region_bound_setup,
    _lean_region_definition,
    _lean_region_flag_setup,
    _lean_region_index_masks,
    _lean_region_indexed_memory_fact_names,
    _lean_region_indexed_memory_lemma_specs,
    _lean_region_indexed_relocation_word_specs,
    _lean_region_memory_lemma_names,
    _lean_region_memory_lemmas,
    _lean_region_memory_setup,
    _lean_region_relocation_memory_setup,
    _lean_region_separation_setup,
    _lean_region_static_memory_lemma_specs,
    _lean_region_static_relocation_word_specs,
    _lean_region_theorem_source,
    _lean_region_value_targets,
    _lean_register_argument_claim,
    _lean_register_offset_witness,
    _lean_register_offset_write,
    _lean_register_output_claim,
    _lean_register_pair,
    _lean_register_relation_pair,
    _lean_relation_constructor,
    _lean_relocations,
    _lean_return_slot_offset_pair,
    _lean_right_append,
    _lean_semantic_bool_expr,
    _lean_semantic_expr,
    _lean_semantic_x87_expr,
    _lean_sorted_span_certificate,
    _lean_span,
    _lean_stack_address_separation_claim,
    _lean_stack_window,
    _lean_stack_window_argument_claim,
    _lean_stack_window_transfer_claim,
    _lean_state_invariant,
    _lean_static_dynamic_pointer_slot,
    _lean_static_proof_context_base_source,
    _lean_static_range,
    _lean_successor_tautology_proof,
    _lean_symbolic_x87_state,
    _lean_targets_definition,
    _lean_value_target,
    _lean_x87_state_only_pair,
    _normalized_behavior_fast_path,
    _normalized_behavior_structure_matches,
    _partition_proof_shards,
    _required_input_pairs,
    _required_input_pairs_from,
    _semantic_masked_successor_shape,
    _semantic_successor_shape,
    _side_coverage_spans,
    _side_padding,
    _sorted_span_certificate,
    _static_index_ranges,
    _whole_program_acceptance_plan,
    _write_reachable_product_local_certificate,
    _write_relational_acceptance_modules,
    _write_relational_external_call_refinement_modules,
    _write_relational_invariant_modules,
    _write_relational_memory_pullback_modules,
    _write_relational_product_graph_modules,
    _write_relational_register_relation_modules,
    _write_relational_segment_refinement_modules,
    _write_relational_static_context_modules,
    _write_sharded_relational_proof,
    _write_stack_separation_modules,
)
from .relational.model import (
    PURE_SEMANTIC_EXPR_OPERATIONS,
    _semantic_constant_bool,
    _semantic_hash,
)
from .relational.schema import (
    FLAG_BITS,
    MACHINE_CALL_ABI_REGISTERS,
    MACHINE_CALL_ABI_TEMPLATES,
    MACHINE_CALL_MAX_ARGUMENT_WORDS,
    MACHINE_CALL_MEMORY_EFFECTS,
    MACHINE_CALL_WORLD_EFFECTS,
    REGISTERS,
    RELATION_CONTRACT_FORMAT,
    RELATIONAL_ACCEPTANCE_THEOREM,
    RELATIONAL_APPROVED_AXIOMS,
    RELATIONAL_ENVIRONMENT_ID,
    RELATIONAL_KERNEL_MODULES,
    RELATIONAL_OBSERVATIONS,
    RELATIONAL_PREPARED_REPORT_FILES,
    RELATIONAL_PROOF_IR_FORMAT,
    RELATIONAL_SEGMENT_CERTIFICATE_FORMAT,
    STAGE_A_RELATIONAL_MODEL_ID,
    STAGE_A_RELATIONAL_PROFILE_ID,
    integer as _integer,
)
from .relational.pipeline import (
    _run_sharded_relational,
    stage_a_check_relational_proof,
    stage_a_prepare_relational,
    stage_a_prove_relational,
)
