import StageA.RelationalNativeSourceReachableBoundaryDomain

namespace StageA.Relational.NativeSource

open StageA.Relational
open StageA.Relational.InterpreterNativeWorld
open StageA.Relational.InterpreterWorldBridge

/-! # Checked admitted source/native response families

This module keeps the external protocol abstract without admitting arbitrary
environment pairs.  A pair is admitted only when every exact lockstep site has
a checked response law.  Returning responses must satisfy the machine ABI,
memory/world footprint, result-value relation, continuation `StateRel`, and
runtime-frame obligations.  Terminating responses must terminate at the same
event index and preserve the shared relational world.

The admission relation contains every pair satisfying those obligations.  A
single canonical pair is retained only to prove that the relation is inhabited;
it does not narrow final acceptance to one fixed response schedule.
-/

/-- Byte-level relation for one dynamically resolved machine-call read span.
Ordinary data bytes may be equal.  A four-byte subspan may instead carry a
checked related machine word, allowing concrete mapped pointers to differ. -/
def MachineCallReadFootprintRelated
    (context : StaticProofContext) (world : RelationalWorld)
    (footprint : MachineCallMemoryFootprint)
    (originalEvent candidateEvent : WorldExternalEvent) : Prop :=
  match footprint.range? originalEvent.state.memory originalEvent.arguments,
      footprint.range? candidateEvent.state.memory candidateEvent.arguments with
  | some originalRange, some candidateRange =>
      originalRange.2 - originalRange.1 = candidateRange.2 - candidateRange.1 /\
        forall offset,
          offset < originalRange.2 - originalRange.1 ->
            originalEvent.state.memory
                (BitVec.ofNat 32 (originalRange.1 + offset)) =
                candidateEvent.state.memory
                  (BitVec.ofNat 32 (candidateRange.1 + offset)) \/
              exists wordOffset,
                wordOffset <= offset /\ offset < wordOffset + 4 /\
                  wordOffset + 4 <= originalRange.2 - originalRange.1 /\
                  wordRelated context.originalPe.imageBase
                    context.candidatePe.imageBase context.codeMap.entries.toList
                    (context.relationalValueTargets world)
                    (Memory.read32 originalEvent.state.memory
                      (BitVec.ofNat 32 (originalRange.1 + wordOffset)))
                    (Memory.read32 candidateEvent.state.memory
                      (BitVec.ofNat 32 (candidateRange.1 + wordOffset)))
  | _, _ => False

/-- Resolve the exact machine-call contract and relate every declared input
read footprint.  This is state indexed, so argument-sized and terminated spans
need not be widened to a fixed generated byte bound. -/
def WorldNativePointedArgumentsRelated
    (context : StaticProofContext) (program : DecodedWorldProgram)
    (site : OpaqueLockstepCallSite)
    (originalEvent candidateEvent : WorldExternalEvent) : Prop :=
  exists callSite contract,
    callSite ∈ program.externalCallSites /\
      site.matchesExternalCallSite context callSite = true /\
      machineImportCallContractById? context callSite.machineContractId =
        some contract /\
      forall footprint, footprint ∈ contract.memoryFootprints ->
        footprint.access = .read ->
          MachineCallReadFootprintRelated context originalEvent.world footprint
            originalEvent candidateEvent

/-- Checked response behavior at one static lockstep site.  Callback and
blocked native actions cannot satisfy either branch. -/
structure CheckedWorldNativeResponseAt
    (context : StaticProofContext) (program : DecodedWorldProgram)
    (site : OpaqueLockstepCallSite)
    (sourceEnvironment : WorldExternalEnvironment)
    (nativeEnvironment : NativeWorldEnvironment) where
  boundaryDomain : CheckedReachableWorldNativeBoundaryDomain context program site
  pointedArguments : forall request, boundaryDomain.Admits request ->
    WorldNativePointedArgumentsRelated context program site request.originalEvent
      (request.candidateWorldEvent site)
  returning : site.disposition = .returns ->
    forall request, boundaryDomain.Admits request ->
      exists candidateResult,
        nativeEnvironment.action request.eventIndex request.candidateEvent
            request.originalEvent.world =
          .returned candidateResult /\
        OpaqueWorldNativeABIResultRelated context program site
          request.originalEvent request.candidateEvent
          (sourceEnvironment.result request.eventIndex request.originalEvent)
          candidateResult
  terminating : site.disposition = .terminates ->
    forall request, boundaryDomain.Admits request ->
      nativeEnvironment.action request.eventIndex request.candidateEvent
          request.originalEvent.world =
        .terminated request.originalEvent.world

theorem CheckedWorldNativeResponseAt.refines
    {context : StaticProofContext} {program : DecodedWorldProgram}
    {site : OpaqueLockstepCallSite}
    {sourceEnvironment : WorldExternalEnvironment}
    {nativeEnvironment : NativeWorldEnvironment}
    (checked : CheckedWorldNativeResponseAt context program site
      sourceEnvironment nativeEnvironment)
    (allRelatedRequestsAdmitted : forall request : WorldNativeBoundaryRequest,
      request.BoundaryRelated context site ->
        checked.boundaryDomain.Admits request) :
    WorldNativeExternalEnvironmentRefinesAt context site sourceEnvironment
      nativeEnvironment := by
  unfold WorldNativeExternalEnvironmentRefinesAt
  cases disposition : site.disposition with
  | returns =>
      intro eventIndex originalEvent candidateEvent boundary
      let request : WorldNativeBoundaryRequest := {
        eventIndex, originalEvent, candidateEvent
      }
      have admitted := allRelatedRequestsAdmitted request boundary
      rcases checked.returning disposition request admitted with
        ⟨candidateResult, actionExact, callSite, contract, callSiteMember,
          siteMatches, contractResolved, originalConforms, candidateConforms,
          registersRelated, resultRelated⟩
      exact ⟨candidateResult, actionExact, resultRelated⟩
  | terminates =>
      intro eventIndex originalEvent candidateEvent boundary
      let request : WorldNativeBoundaryRequest := {
        eventIndex, originalEvent, candidateEvent
      }
      exact checked.terminating disposition request
        (allRelatedRequestsAdmitted request boundary)

/-- Program-wide response schedule.  Static coverage is checked once, while
the response theorem remains quantified over every event index and every
boundary-related pair of concrete events. -/
structure CheckedWorldNativeResponseSchedule
    (context : StaticProofContext) (program : DecodedWorldProgram)
    (candidate : ExactNativeWorldProgram)
    (sites : List OpaqueLockstepCallSite)
    (sourceEnvironment : WorldExternalEnvironment) where
  contextValid : context.StructurallyValid
  originalCovered : opaqueLockstepCallSitesCoverExternalSites context
    program.externalCallSites sites = true
  sitesUnique : opaqueLockstepCallSiteIdsUnique sites = true
  sitesValid : sites.all (OpaqueLockstepCallSite.staticValid context) = true
  responses : forall site, site ∈ sites ->
    CheckedWorldNativeResponseAt context program site sourceEnvironment
      candidate.environment
  allRelatedRequestsAdmitted : forall site (member : site ∈ sites)
      (request : WorldNativeBoundaryRequest),
    request.BoundaryRelated context site ->
      (responses site member).boundaryDomain.Admits request

def CheckedWorldNativeResponseSchedule.externalEvidence
    {context : StaticProofContext} {program : DecodedWorldProgram}
    {candidate : ExactNativeWorldProgram}
    {sites : List OpaqueLockstepCallSite}
    {sourceEnvironment : WorldExternalEnvironment}
    (schedule : CheckedWorldNativeResponseSchedule context program candidate
      sites sourceEnvironment) :
    ExactWorldNativeExternalEvidence context program candidate sites
      sourceEnvironment := {
  contextValid := schedule.contextValid
  originalCovered := schedule.originalCovered
  sitesUnique := schedule.sitesUnique
  sitesValid := schedule.sitesValid
  refines := fun site member => (schedule.responses site member).refines
    (schedule.allRelatedRequestsAdmitted site member)
}

theorem CheckedWorldNativeResponseSchedule.returningABI
    {context : StaticProofContext} {program : DecodedWorldProgram}
    {candidate : ExactNativeWorldProgram}
    {sites : List OpaqueLockstepCallSite}
    {sourceEnvironment : WorldExternalEnvironment}
    (schedule : CheckedWorldNativeResponseSchedule context program candidate
      sites sourceEnvironment)
    (site : OpaqueLockstepCallSite) (member : site ∈ sites)
    (returns : site.disposition = .returns) :
    forall eventIndex originalEvent candidateEvent,
      OpaqueLockstepBoundaryRelated context site originalEvent
        (nativeExternalEventToWorldExternalEvent candidateEvent site.id
          originalEvent.world) ->
      exists candidateResult,
        candidate.environment.action eventIndex candidateEvent
            originalEvent.world = .returned candidateResult /\
        OpaqueWorldNativeABIResultRelated context program site originalEvent
          candidateEvent (sourceEnvironment.result eventIndex originalEvent)
          candidateResult :=
  fun eventIndex originalEvent candidateEvent boundary =>
    (schedule.responses site member).returning returns
      { eventIndex, originalEvent, candidateEvent }
      (schedule.allRelatedRequestsAdmitted site member
        { eventIndex, originalEvent, candidateEvent } boundary)

/-- The broad admission predicate used by final acceptance.  It characterizes
all response schedules satisfying the checked lockstep, ABI, and launch
obligations; it is not equality with a distinguished environment pair. -/
structure AdmittedWorldNativeResponsePair
    (context : StaticProofContext) (sites : List OpaqueLockstepCallSite)
    (compilation : ExactNativeCompilation)
    (sourceEnvironment : WorldExternalEnvironment)
    (nativeEnvironment : NativeWorldEnvironment) where
  responseSchedule : CheckedWorldNativeResponseSchedule context
    (exactNativeCompilationAtEnvironments compilation sourceEnvironment
      nativeEnvironment).project.worldProgram
    (exactNativeCompilationAtEnvironments compilation sourceEnvironment
      nativeEnvironment).machineAuthority.program
    sites sourceEnvironment
  sourceFamily : CheckedNativeSourceLaunchFamily
    (exactNativeCompilationAtEnvironments compilation sourceEnvironment
      nativeEnvironment).project
  launchRealizable : NativeCompilationLaunchRealizable
    (exactNativeCompilationAtEnvironments compilation sourceEnvironment
      nativeEnvironment).machineAuthority

def AdmittedWorldNativeResponsePair.toConcretePair
    {context : StaticProofContext} {sites : List OpaqueLockstepCallSite}
    {compilation : ExactNativeCompilation}
    {sourceEnvironment : WorldExternalEnvironment}
    {nativeEnvironment : NativeWorldEnvironment}
    (admitted : AdmittedWorldNativeResponsePair context sites compilation
      sourceEnvironment nativeEnvironment) :
    CheckedConcreteWorldNativeEnvironmentPair context sites compilation := {
  sourceEnvironment := sourceEnvironment
  nativeEnvironment := nativeEnvironment
  externalEvidence := admitted.responseSchedule.externalEvidence
  returningABI := fun site member returns =>
    admitted.responseSchedule.returningABI site member returns
  sourceFamily := admitted.sourceFamily
  launchRealizable := admitted.launchRealizable
}

/-- An inhabited broad response family.  `canonical` is only the constructive
non-vacuity witness; `Related` remains the full admission predicate. -/
structure CheckedWorldNativeAdmittedResponseFamily
    (context : StaticProofContext) (sites : List OpaqueLockstepCallSite)
    (compilation : ExactNativeCompilation) where
  canonicalSourceEnvironment : WorldExternalEnvironment
  canonicalNativeEnvironment : NativeWorldEnvironment
  canonical : AdmittedWorldNativeResponsePair context sites compilation
    canonicalSourceEnvironment canonicalNativeEnvironment

def CheckedWorldNativeAdmittedResponseFamily.Related
    {context : StaticProofContext} {sites : List OpaqueLockstepCallSite}
    {compilation : ExactNativeCompilation}
    (_family : CheckedWorldNativeAdmittedResponseFamily context sites
      compilation)
    (sourceEnvironment : WorldExternalEnvironment)
    (nativeEnvironment : NativeWorldEnvironment) : Prop :=
  Nonempty (AdmittedWorldNativeResponsePair context sites compilation
    sourceEnvironment nativeEnvironment)

theorem CheckedWorldNativeAdmittedResponseFamily.realizable
    {context : StaticProofContext} {sites : List OpaqueLockstepCallSite}
    {compilation : ExactNativeCompilation}
    (family : CheckedWorldNativeAdmittedResponseFamily context sites
      compilation) :
    exists sourceEnvironment nativeEnvironment,
      family.Related sourceEnvironment nativeEnvironment := by
  exact ⟨family.canonicalSourceEnvironment, family.canonicalNativeEnvironment,
    ⟨family.canonical⟩⟩

def CheckedWorldNativeAdmittedResponseFamily.admittedEvidence
    {context : StaticProofContext} {sites : List OpaqueLockstepCallSite}
    {compilation : ExactNativeCompilation}
    (family : CheckedWorldNativeAdmittedResponseFamily context sites
      compilation) :
    CheckedNativeSourceAdmittedPairEvidence context sites compilation
      family.Related := {
  pairRealizable := family.realizable
  externalEvidenceAt := fun _source _native related => by
    rcases related with ⟨admitted⟩
    exact admitted.responseSchedule.externalEvidence
  sourceFamilyAt := fun _source _native related => by
    rcases related with ⟨admitted⟩
    exact admitted.sourceFamily
  launchRealizableAt := fun _source _native related => by
    rcases related with ⟨admitted⟩
    exact admitted.launchRealizable
}

def CheckedWorldNativeAdmittedResponseFamily.canonicalConcretePair
    {context : StaticProofContext} {sites : List OpaqueLockstepCallSite}
    {compilation : ExactNativeCompilation}
    (family : CheckedWorldNativeAdmittedResponseFamily context sites
      compilation) :
    CheckedConcreteWorldNativeEnvironmentPair context sites compilation :=
  family.canonical.toConcretePair

end StageA.Relational.NativeSource
